version: '3'

services:
  nigelmes:
    build: ./Part 5/
    container_name: temp
  proxynginx:
    image: nginx
    volumes:
      - ./Part 6/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080
